"""Actualizacion de tabla de menu

Revision ID: 18f2863b3ef7
Revises: be4f33d75542
Create Date: 2023-03-03 19:59:58.929911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f2863b3ef7'
down_revision = 'be4f33d75542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('disonibilidad', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tipo', sa.String(length=120), nullable=True))
        batch_op.alter_column('detalle',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('detalle',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('tipo')
        batch_op.drop_column('disonibilidad')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
