"""Actualizando modelos

Revision ID: 23568d90de68
Revises: 9540882b3e7a
Create Date: 2023-03-06 19:12:43.347119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23568d90de68'
down_revision = '9540882b3e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('stock')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
