"""Creando tabla menu

Revision ID: 3f1cbaaf6cef
Revises: 562819c9ebcd
Create Date: 2023-03-02 17:57:24.053094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1cbaaf6cef'
down_revision = '562819c9ebcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('precio')

    # ### end Alembic commands ###
