"""Creando modelo de Menu

Revision ID: 562819c9ebcd
Revises: 1c1252ad6ada
Create Date: 2023-03-02 17:08:51.153335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562819c9ebcd'
down_revision = '1c1252ad6ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('detalle', sa.String(length=120), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu')
    # ### end Alembic commands ###
